Repository JaRutkowski/eLibrary, pull requests merged in 2020-11, with the labels that each got.

#243 JaRutkowski #41 Client Web-app
  elibrary-hibernate/pom.xml
  elibrary-rest-api/pom.xml
  elibrary-web-front/.env
  elibrary-web-front/.gitignore
  elibrary-web-front/README.md
  elibrary-web-front/package.json
  elibrary-web-front/pom.xml
  elibrary-web-front/public/favicon.ico
  elibrary-web-front/public/index.html
  elibrary-web-front/public/logo192.png
  elibrary-web-front/public/logo512.png
  elibrary-web-front/public/manifest.json
  elibrary-web-front/public/robots.txt
  elibrary-web-front/src/App.css
  elibrary-web-front/src/App.js
  elibrary-web-front/src/App.test.js
  elibrary-web-front/src/index.css
  elibrary-web-front/src/index.js
  elibrary-web-front/src/logo.svg
  elibrary-web-front/src/reportWebVitals.js
  elibrary-web-front/src/setupTests.js
  elibrary-web-front/yarn.lock
  elibrary-web-rest-api/.gitignore
  elibrary-web-rest-api/mvnw
  elibrary-web-rest-api/mvnw.cmd
  elibrary-web-rest-api/pom.xml
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/ElibraryWebRestApiApplication.java
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/ServletInitializer.java
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/configuration/CorsConfiguration.java
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/controller/UserDataController.java
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/controller/api/UserDataApi.java
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/model/domain/UserData.java
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/model/repository/UserDataRepository.java
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/service/UserDataService.java
  elibrary-web-rest-api/src/main/resources/application-dev.properties
  elibrary-web-rest-api/src/main/resources/application.properties
  elibrary-web-rest-api/src/test/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/ElibraryWebRestApiApplicationTests.java
  pom.xml
Labels: enhancement, technology

#247 MaSzymszyk #63 Incoherence in worker employment
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabComposePageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabDraftPageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabOutboxPageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabTemplatePageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/FontPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/PasswordChangePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/PersonalDataChangePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/ThemePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/LogInEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/RegistrationEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/ClientAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabClientEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabLoanServiceEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabWorkerEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/WorkerAddModEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Query.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Validator.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/watchservice/WatchServiceDirectory.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/ClientTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/RegisteredClientTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/WorkerTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/initializator/FeedAdministratorDataProcess.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/common/Utils.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Common.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Constants.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Query.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/SystemProperties.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/SystemProperties_.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/UserAccount.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/UserData.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/Client.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/Worker.java
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-ddl-20201118172712UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/init-sequences-changelog.xml
  elibrary-rest-api/src/main/java/com/javafee/elibrary/rest/api/controller/monitor/MonitorApi.java
  elibrary-rest-api/src/main/java/com/javafee/elibrary/rest/api/repository/dto/api/UserAccount.java
  elibrary-rest-api/src/main/java/com/javafee/elibrary/rest/api/repository/dto/common/UserData.java
  elibrary-rest-api/src/main/java/com/javafee/elibrary/rest/api/repository/repository/AuthorizationRepository.java
Labels: bug, elibrary-rest-api, enhancement

#252 MaSzymczyk #248 Not able to login as the administrator
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-20201123164445UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/init-sequences-changelog.xml
Labels: CRITICAL, bug

#254 MaSzymczyk #253 Changelog after DDL changes
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-20201123161902UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/init-sequences-changelog.xml
  elibrary-hibernate/src/main/resources/db/changelog/truncate-all-cascade-changelog.xml
Labels: technology

#257 MaSzymczyk #255 DML setup for Michal
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-20201125160909UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/init-sequences-changelog.xml
  elibrary-hibernate/src/main/resources/db/changelog/truncate-all-cascade-changelog.xml
Labels: data
