Repository JaRutkowski/eLibrary, pull requests merged in 2020-04, with the labels that each got.

#148 #135 settings system data
  elibrary-core/diary/dia_projects/002#135_gliffy_settings_system_data_v0.2.pdf
  elibrary-core/diary/dia_projects/003#142_gliffy_about_v0.1.pdf
  elibrary-core/diary/dia_projects/template/NUMBER#BRANCHNUMBER_TOOL_BRANCHNAME_vVERSION.docx
  elibrary-core/diary/eLibrary-guide-pl.pptx
  elibrary-core/source/resources/images/btnCheckHealth-ico.png
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/MailSenderEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemDataFeedingPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemParametersPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemProcessesPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/LogInEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/RegistrationEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabLoanServiceEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Constants.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/SystemProperties.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/networkservice/INetworkService.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/networkservice/NetworkServiceListener.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/timerservice/ITimerService.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/watchservice/IWatchService.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/watchservice/WatchServiceDirectory.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/watchservice/WatchServiceListener.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/mail/MailSender.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/LoanTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/SystemDataFeedingTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/pojo/SystemDataFeedingPojo.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/initializator/FeedLibraryDataProcess.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/initializator/FeedSystemDataProcess.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/initializator/FeedSystemParametersProcess.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SettingsPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemDataFeedingPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemDataFeedingTablePanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemParametersPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemProcessesPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/utils/SystemDataFeedingTableCellRenderer.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/common/BasePanel.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/common/Utils.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jcheckbox/CustomJCheckBox.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jspinner/CustomJSpinner.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jspinner/DoubleJSpinner.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jtable/CustomJTable.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jtable/actiontable/Action.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jtable/actiontable/ActionJTable.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jtable/actiontable/ActionJTableBtnEditor.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jtable/actiontable/ActionJTableBtnPanel.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jtable/actiontable/ActionJTableBtnRenderer.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jtable/actiontable/ActionWrapper.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Common.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Constants.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Query.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/association/MessageType.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/SystemData.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/SystemParameter.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/LibraryBranchData.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/LibraryData.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/LibrarySystemData.java
Labels: enhancement

#156 MaSzymczyk #155 Restore #143
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
Labels: bug

#160 MaSzymczyk #120 Unexpected refresh button behavior
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/BookAddModEvent.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/tabbedform/books/frames/BookAddModFrame.java
Labels: bug

#161 MaSzymczyk #152 Worker connection to library data
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/RegistrationEvent.java
Labels: refactoring

#164 MaSzymczyk #163 Generated password length error
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Constants.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemParametersPanel.java
Labels: bug

#166 MaSzymczyk #165 Min max password parametrization
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/PasswordChangePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemParametersPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/ClientAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/WorkerAddModEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Constants.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/initializator/FeedSystemParametersProcess.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemParametersPanel.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Constants.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Query.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/LibraryData.java
Labels: enhancement

#168 MaSzymczyk #153 Validate e-mail configuration
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/PasswordChangePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabClientEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
Labels: enhancement

#169 JaRutkowski #159 Common data base connection
  elibrary-hibernate/pom.xml
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/HibernateUtil.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Constants.java
  elibrary-hibernate/src/main/resources/application.properties
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-20200422201731UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/truncate-all-cascade-changelog.xml
  elibrary-hibernate/src/main/resources/liquibase.properties
  elibrary-hibernate/src/main/resources/profiles/dev/application.properties
  elibrary-hibernate/src/main/resources/profiles/prod/application.properties
Labels: enhancement, technology

#171 MaSzymczyk #170 Refactor checkEmailServerConnectivity
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemParametersPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabClientEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
Labels: refactoring

#172 MaKocik #162 E-mail validation
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemParametersPanelEvent.java
Labels: bug
