Repository JaRutkowski/eLibrary, pull requests merged in 2020-01, with the labels that each got.

#88 MaKocik #87 No warning dialog on draft page
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/emailform/TabDraftPageEvent.java
Labels: bug

#92 MaSzymczyk #89 No validation message dialog for email outbox tab
  elibrary-core/source/src/controller/java/com/javafee/emailform/TabOutboxPageEvent.java
Labels: bug

#94 JaRutkowski #93 Critical StackOverflowError in worker
  elibrary-core/source/src/controller/java/com/javafee/tabbedform/TabWorkerEvent.java
Labels: CRITICAL, bug

#97 JaRutkowski #71 System data and parameters handling
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/LogInEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/initializator/FeedMessageTypesProcess.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Constants.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Query.java
Labels: bug, enhancement

#98 MaSzymczyk #90 Information dialog for user approvals
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/tabbedform/TabWorkerEvent.java
Labels: bug
