Repository JaRutkowski/eLibrary, pull requests merged in 2020-08, with the labels that each got.

#217 JaRutkowski #70 Problem with e-mail sender refresh after user removal
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabComposePageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabDraftPageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabOutboxPageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/ClientAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabClientEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/DraftTableModel.java
Labels: bug

#228 #209 e mail server internet monitor
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemMonitorPanelEvent.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemMonitorPanel.java
Labels: enhancement

#232 MaSzymczyk #186 elibrary-rest-api gitignore
  elibrary-rest-api/.gitignore
Labels: elibrary-rest-api, refactoring

#233 MaSzymczyk #202 Registration date
  .gitignore
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/RegistrationEvent.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/UserData.java
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-ddl-20200803134708UTC.xml
Labels: enhancement

#234 MaSzymczyk #205 Redundant more element
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
Labels: bug

#235 MaSzymczyk #218 Deleted user alias
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/DraftTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/OutboxTableModel.java
Labels: bug

#236 MaSzymczyk #230 Deleted users
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabComposePageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabDraftPageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabOutboxPageEvent.java
Labels: bug

#237 MaSzymczyk #220 Label alignment
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/FontPanel.java
Labels: bug
