Repository JaRutkowski/eLibrary, pull requests merged in 2020-07, with the labels that each got.

#204 #193 cities combo box improvment
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/PersonalDataChangePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemParametersPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/RegistrationEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/ClientAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/WorkerAddModEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Constants.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/SystemProperties.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/ClientTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/model/WorkerTableModel.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/initializator/FeedSystemParametersProcess.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/ws/FetchCitiesWithElibraryRestApiWS.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/unicomponent/action/CitiesJComboBoxAction.java
  elibrary-core/source/src/view/forms/com/javafee/elibrary/core/startform/MainSplashScreen.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemParametersPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/startform/RegistrationPanel.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jcombobox/citiescombobox/CitiesJComboBox.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Constants.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Query.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/association/City.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/UserData.java
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-20200703213344UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-ddl-20200703213345UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/truncate-all-cascade-changelog.xml
Labels: bug, enhancement

#206 MaSzymczyk #200 API no connection
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/ws/FetchCitiesWithElibraryRestApiWS.java
Labels: bug

#210 MaSzymczyk #208 API services monitor
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemMonitorPanelEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Constants.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/SystemProperties.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/process/ws/FetchCitiesWithElibraryRestApiWS.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SettingsPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemMonitorPanel.java
  elibrary-hibernate/src/main/resources/application.properties
  elibrary-hibernate/src/main/resources/profiles/dev/application.properties
  elibrary-hibernate/src/main/resources/profiles/prod/application.properties
  elibrary-rest-api/src/main/java/com/javafee/elibrary/rest/api/controller/monitor/Monitor.java
  elibrary-rest-api/src/main/java/com/javafee/elibrary/rest/api/controller/monitor/MonitorApi.java
Labels: enhancement

#211 MaSzymczyk #201 DB connection information
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemMonitorPanelEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemMonitorPanel.java
  elibrary-hibernate/src/main/resources/application.properties
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-20200722123232UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/truncate-all-cascade-changelog.xml
  elibrary-hibernate/src/main/resources/profiles/prod/application.properties
Labels: enhancement

#212 JaRutkowski #199 Sequences
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/init-sequences-changelog.xml
Labels: CRITICAL, bug, technology

#216 JaRutkowski #214 E-mail server connection check failing
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemParametersPanelEvent.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemMonitorPanel.java
Labels: CRITICAL, bug

#215 JaRutkowski #213 Feed Administrator Data failing
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/common/Query.java
Labels: CRITICAL, bug
