Repository JaRutkowski/eLibrary, pull requests merged in 2020-03, with the labels that each got.

#130 #42 image view for book volumes
  elibrary-core/pom.xml
  elibrary-core/source/resources/images/btnChooseFile-ico.png
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabTemplatePageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/BookAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabBookEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabLibraryEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Constants.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/tabbedform/books/BookTablePanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/tabbedform/books/frames/BookAddModFrame.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/tabbedform/books/frames/BookDataPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/tabbedform/library/LibraryTablePanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/uniform/ImagePanel.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/common/Utils.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/unicomponent/jscrollpain/CustomJScrollPane.java
  elibrary-hibernate/pom.xml
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/FileEntity.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/extdata/ExtFileMetadata.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/Book.java
  pom.xml
Labels: enhancement

#131 JaRutkowski #127 Book dictionaries
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/tabbedform/books/frames/BookAddModFrame.java
Labels: CRITICAL, bug

#133 JaRutkowski #132 Version v2.0
  elibrary-core/diary/dia_sql/backup/v2.0/elibrary-v2.0.backup
  elibrary-core/diary/dia_sql/com_user_data_e_mail.sql
  elibrary-core/diary/dia_sql/mes_message.sql
  elibrary-core/diary/dia_sql/mes_message_type.sql
  elibrary-core/diary/dia_sql/mes_recipient.sql
  elibrary-core/diary/dia_sql/system_properties_id_user_data.sql
  elibrary-core/diary/dia_sql/system_properties_template_directory.sql
  elibrary-core/source/resources/images/splashScreen.jpg
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/message/Message.java
Labels: version

#143 MaSzymczyk #136 Change year in footer
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
Labels: bug

#144 MaSzymczyk #137 Unnecessary dialog
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/RegistrationEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/ClientAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/WorkerAddModEvent.java
Labels: bug

#147 MaSzymczyk #146 Iteration over all users collection
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/startform/RegistrationEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/ClientAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/WorkerAddModEvent.java
Labels: refactoring
