Repository JaRutkowski/eLibrary, pull requests merged in 2021-01, with the labels that each got.

#284 #282 current build data and release data
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/aboutform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemInstallationPanelEvent.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Common.java
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/Constants.java
  elibrary-core/source/src/view/forms/com/javafee/elibrary/core/aboutform/AboutForm.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SettingsPanel.java
  elibrary-core/source/src/view/panels/com/javafee/elibrary/core/settingsform/SystemInstallationPanel.java
  elibrary-core/source/src/view/utils/com/javafee/elibrary/core/common/Utils.java
Labels: elibrary-rest-api, enhancement

#286 AJPattar #261 Conflicted lombok versions
  pom.xml
Labels: bug

#289 JaRutkowski #277 Version v4.0
  elibrary-core/pom.xml
  elibrary-core/source/resources/images/btnTreeMenuClose-ico_shallow.png
  elibrary-core/source/resources/images/btnTreeMenuOpen-ico_shallow.png
  elibrary-core/source/resources/images/splashScreen.jpg
  elibrary-core/source/resources/images/splashScreen_v1_2017.jpg
  elibrary-core/source/resources/images/splashScreen_v3_2020.jpg
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-hibernate/pom.xml
  elibrary-hibernate/src/main/resources/profiles/dev/application.properties
  elibrary-hibernate/src/main/resources/profiles/prod/application.properties
  elibrary-rest-api/pom.xml
  elibrary-web-front/pom.xml
  elibrary-web-front/src/Demo/Tables/Reservations.js
  elibrary-web-rest-api/pom.xml
  elibrary-web-rest-api/src/main/java/com/javafee/elibrary/web/rest/api/elibrarywebrestapi/model/dto/LendDto.java
  pom.xml
Labels: version

#290 JaRutkowski #277 Version v4.0
  elibrary-core/source/resources/messages.properties
  elibrary-core/source/resources/messages_en.properties
  elibrary-core/source/resources/messages_pl.properties
  elibrary-hibernate/src/main/resources/db-changelog-master.xml
  elibrary-hibernate/src/main/resources/db/changelog/db-changelog-20210131103122UTC.xml
  elibrary-hibernate/src/main/resources/db/changelog/init-sequences-changelog.xml
  elibrary-hibernate/src/main/resources/db/changelog/truncate-all-cascade-changelog.xml
Labels: version
