Repository JaRutkowski/eLibrary, pull requests merged in 2023-01, with the labels that each got.

#357 #352 micro skeleton DONE
  elibrary-micro/.gitignore
  elibrary-micro/Dockerfile
  elibrary-micro/Procfile
  elibrary-micro/README.md
  elibrary-micro/deployment.yml
  elibrary-micro/docker-compose.yml
  elibrary-micro/mvnw
  elibrary-micro/mvnw.cmd
  elibrary-micro/pom.xml
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/MicroApplication.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/config/CommandRunnerConfig.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/config/Constants.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/config/PostgreSQLDatabaseConfig.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/config/SystemProperties.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/config/WebConfig.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/config/filter/FilterRegistry.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/config/filter/SessionLocaleFilter.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/controller/api/TestControllerApi.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/controller/api/impl/TestController.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/apiversion/ApiVersion.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/apiversion/handler/ApiVersionRequestMappingHandlerMapping.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/aspect/AutoLoggableAspect.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/aspect/AutoMeasuringTimeAspect.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/aspect/annotation/AutoLoggable.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/aspect/annotation/AutoMeasuringTime.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/aspect/joinpoint/AutoLoggableJoinPoint.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/aspect/joinpoint/AutoMeasuringTimeJoinPoint.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/aspect/joinpoint/TestGeneralLoggingJoinPoint.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/infrastructure/exception/CustomGlobalExceptionHandler.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/model/domain/Test.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/model/repository/TestRepository.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/service/TestService.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/service/dto/ELibraryMicroExceptionDto.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/service/dto/TestDto.java
  elibrary-micro/src/main/java/com/javafee/elibrary/micro/service/impl/TestServiceImpl.java
  elibrary-micro/src/main/resources/application-ci.properties
  elibrary-micro/src/main/resources/application-dev.properties
  elibrary-micro/src/main/resources/application-docker.properties
  elibrary-micro/src/main/resources/application-prod.properties
  elibrary-micro/src/main/resources/application.properties
  elibrary-micro/src/main/resources/logback-spring.xml
  elibrary-micro/src/main/resources/messages.properties
  elibrary-micro/src/main/resources/messages_en.properties
  elibrary-micro/src/main/resources/messages_pl.properties
  elibrary-micro/src/main/resources/readme/advise-method.png
  elibrary-micro/src/main/resources/readme/aop-advice.png
  elibrary-micro/system.properties
  pom.xml
Labels: technology, data, micro

#361 #149 Enter key listener
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabComposePageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabDraftPageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabOutboxPageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/emailform/TabTemplatePageEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/FontPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/PasswordChangePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/PersonalDataChangePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemDataFeedingPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemMonitorPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemParametersPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/SystemProcessesPanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/settingsform/ThemePanelEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/Actions.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/BookAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/ClientAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/LibraryAddModEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabAdmDictionaryEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabBookEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabBrowseReservationEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabCreateReservationEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabLibraryEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabLoanServiceEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/TabWorkerEvent.java
  elibrary-core/source/src/controller/java/com/javafee/elibrary/core/tabbedform/WorkerAddModEvent.java
Labels: bug

#369 #363 uprage tech stack in the core,hibernate
  elibrary-core/pom.xml
  elibrary-core/source/src/controller/utils/com/javafee/elibrary/core/common/HTMLProcessor.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/HibernateDao.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dao/HibernateUtil.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/common/SystemProperties.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/Client.java
  elibrary-hibernate/src/main/java/com/javafee/elibrary/hibernate/dto/library/LibraryBranchData.java
  pom.xml
Labels: enhancement, technology
